
include: package:flutter_lints/flutter.yaml

linter:
  rules:
analyzer: 
  plugins: 
    - custom_lint
  errors: 
    invalid_annotation_target: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'